---
- name: Create container
  lxd_container:
    name: "{{ item.name }}"
    config: "{{ (item.config | default({})) | combine({
        'boot.autostart': item.autostart | default(cc__container_default_autostart),
        'limits.cpu': item.limits_cpu | default(cc__container_default_limits_cpu),
        'limits.cpu.allowance': item.limits_cpu_allowance | default(cc__container_default_limits_cpu_allowance),
        'limits.memory': item.limits_memory | default(cc__container_default_limits_memory),
        'security.nesting': item.security_nesting | default(cc__container_default_security_nesting),
        'security.privileged': item.security_privileged | default(cc__container_default_security_privileged)
        }) }}"
    devices: "{{ item.devices | default(omit) }}"
    source:
      alias: "{{ item.source_alias | default(cc__container_default_source_alias) }}"
      mode: pull
      protocol: "{{ item.source_protocol | default(cc__container_default_source_protocol) }}"
      server: "{{ item.source_server | default(cc__container_default_source_server) }}"
      type: "{{ item.source_type | default(cc__container_default_source_type) }}"
    profiles: "{{ item.profiles | default(cc__container_default_profiles) }}"
    wait_for_ipv4_addresses: "{{ item.wait_for_ipv4_addresses | default(cc__container_default_wait_for_ipv4_addresses) }}"
