---
- name: Create container
  lxd_container:
    name: "{{ item.name }}"
    config: "{{ cc__container_default_config | combine(item.config | default({})) }}"
    devices: "{{ item.devices | default(omit) }}"
    source: "{{ cc__container_default_source | combine(item.source | default({})) }}"
    profiles: "{{ item.profiles | default(cc__container_default_profiles) }}"
    wait_for_ipv4_addresses: "{{ item.wait_for_ipv4_addresses | default(cc__container_default_wait_for_ipv4_addresses) }}"
