---
- name: Create container
  lxd_container:
    name: "{{ item.name }}"
    config: "{{ item.config | combine({
        'boot.autostart': item.config['boot.autostart'] | default(cc__container_default_autostart),
        'limits.cpu': item.config['limits.cpu'] | default(cc__container_default_limits_cpu),
        'limits.cpu.allowance': item.config['limits.cpu.allowance'] | default(cc__container_default_limits_cpu_allowance),
        'limits.memory': item.config['limits.memory'] | default(cc__container_default_limits_memory),
        'security.nesting': item.config['security.nesting'] | default(cc__container_default_security_nesting),
        'security.privileged': item.config['security.privileged'] | default(cc__container_default_security_privileged)
        }) }}"
    devices: "{{ item.devices | default(omit) }}"
    source:
      alias: "{{ item.source_alias | default(cc__container_default_source_alias) }}"
      mode: pull
      protocol: "{{ item.source_protocol | default(cc__container_default_source_protocol) }}"
      server: "{{ item.source_server | default(cc__container_default_source_server) }}"
      type: "{{ item.source_type | default(cc__container_default_source_type) }}"
    profiles: "{{ item.profiles | default(cc__container_default_profiles) }}"
    wait_for_ipv4_addresses: "{{ item.wait_for_ipv4_addresses | default(cc__container_default_wait_for_ipv4_addresses) }}"
