---
# See https://archive.fo/6VdpA
# Can't loop and delegate a role at the same time...
- name: Run coaxial.lxd role
  import_role:
    name: coaxial.lxd
  delegate_to: "{{ container.name }}"
  no_log: false

- name: Create test profile
  lxd_profile:
    name: testprofile
    devices:
      eth0:
        name: eth0
        nictype: bridged
        parent: lxdbr0
        type: nic
  delegate_to: "{{ container.name }}"
  no_log: false
