---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ubuntu-xenial
    alias: ubuntu/xenial
  - name: ubuntu-bionic
    alias: ubuntu/bionic
  - name: ubuntu-cosmic
    alias: ubuntu/cosmic

provisioner:
  name: ansible
  playbooks:
    create: ../create.yml
    destroy: ../destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
  # FIXME Idempotence disabled pending Ansible 2.6.3 release, cf issue #2
  test_sequence: ['lint', 'destroy', 'dependency', 'syntax', 'create', 'prepare', 'converge', 'side_effect', 'verify', 'destroy']
verifier:
  name: testinfra
  lint:
    name: flake8
