---
- name: Converge
  hosts: all
  vars:
    cc__containers:
      - name: test-container-1
      - name: test-container-2
        source_alias: 16.04
        devices:
          eth1:
            name: eth1
            nictype: macvlan
            parent: lxdbr0
            type: nic
            ipv4.address: 10.100.12.10
        config:
          boot.autostart: "false"
          limits.cpu: 1
          limits.cpu_allowance: 90%
          limits.memory: 512MB
          security.nesting: "true"
          security.privileged: "true"
          user.network-config: |
            version: 1
            config:
              - type: physical
                name: eth0
                subnets:
                  - type: static
                    address: 10.100.11.10
  tasks:
    - name: Run role
      include_role:
        name: ansible-role-create-lxd-container
      with_items: "{{ cc__containers }}"
